### ISSUE TITLE
Release Version 2.0

### ISSUE THREAD

**Issue by bfwg** [bfwg/ngx-drag-scroll#66]
Hey @joejordanbrown, 

I've created this issue to track the progress of release version 2.0. We should probably merge `v2-refactor` branch to `develop` branch. What do yo think?

**Comment by joejordanbrown** [comment]
@bfwg 

Yes that sounds like a good idea. Make sure you have merged everything from develop to master then merge this branch into develop. You might have to rework the branches first so you don't get conflicts about develop being ahead of this branch because it isn't You could always delete develop after the merge and then clone this branch name it develop branch and set as default. Once this develop branch is the master it would be best to rename the current master branch to the version 1 and keep old versions in branches.

**Comment by bfwg** [comment]
@joejordanbrown 

Sorry for the late response. Yes, I'll create a PR sometime this weekend for merging v2-refactor back to develop.

**Comment by bfwg** [comment]
@joejordanbrown 

I have prepared a PR for 2.0 release merge. Can you review it when you are free? I also let a small question in the PR's comment. Thanks!
